/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAO;
import com.sun.jdi.connect.spi.Connection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Input;
import model.InputInfo;

/**
 *
 * @author khact
 */
public class InputInfoView extends javax.swing.JFrame implements ActionListener{

    private ArrayList<InputInfo> list;
    DefaultTableModel model;

    /**
     * Creates new form InputInfoView
     */
    public InputInfoView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý đơn xuất");
        back.addActionListener(this);
        list = new DAO().getListInputInfo();
        model = (DefaultTableModel) InputInfoTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã nhập sản phẩm","mã sản phẩm","Mã phiếu nhập", "Số lượng nhập","Giá nhập","Giá bán","Trạng thái"
        });
        showtableInputInfoView();
    }
  int i=1;
    private void showtableInputInfoView() {
               for (InputInfo inputInfo : list) {
            model.addRow(new Object[]{
                i++,inputInfo.getInputInfoId(),inputInfo.getItemId(),inputInfo.getInputId(),inputInfo.getQuantity(),inputInfo.getInputPrice(),inputInfo.getOutputPrice(),inputInfo.getInputInfoStatus()
            });

        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        InputInfoTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtitemId = new javax.swing.JTextField();
        txtInputId2 = new javax.swing.JTextField();
        txtinputPrince = new javax.swing.JTextField();
        txtOutputPrice = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtIInputInfoId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQuantityInput = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        btnAddinputInfo = new javax.swing.JButton();
        btnDeleteInputInfo = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(InputInfoTable);

        jLabel9.setText("Số lượng");

        jLabel10.setText("Giá mua");

        jLabel11.setText("Giá bán");

        jLabel12.setText("Trạng thái");

        jLabel4.setText("SẢN PHẨM NHẬP");

        jScrollPane3.setViewportView(txtQuantityInput);

        jLabel6.setText("Mã nhập sản phẩm");

        btnAddinputInfo.setText("Thêm sản phẩm nhập");
        btnAddinputInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddinputInfoActionPerformed(evt);
            }
        });

        btnDeleteInputInfo.setText("Xóa sản phẩm nhập");
        btnDeleteInputInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInputInfoActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã phiếu nhập");

        jLabel1.setText("Mã sản phẩm");

        back.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnAddinputInfo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtInputId2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtitemId, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtIInputInfoId, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtOutputPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtinputPrince))
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btnDeleteInputInfo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(659, 659, 659)
                    .addComponent(jLabel6)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtIInputInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtitemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInputId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtinputPrince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOutputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddinputInfo)
                            .addComponent(btnDeleteInputInfo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jLabel6)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddinputInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddinputInfoActionPerformed
        InputInfo inputInfo = new InputInfo();
        if (txtIInputInfoId.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập Mã nhập sản phẩm");
        } else {
            try {
                inputInfo.setInputInfoId(Integer.parseInt(txtIInputInfoId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Mã nhập sản phẩm chỉ nhận kí tự số và là duy nhất");

            }
            try {
                inputInfo.setItemId(Integer.parseInt(txtitemId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã sản phẩm là số");
            }
        }
        try {
            inputInfo.setInputId(Integer.parseInt(txtInputId2.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã phiếu nhập sản phẩm là số");
        }
        try {
            inputInfo.setQuantity(Float.parseFloat(txtQuantityInput.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số lượng nhập không hợp lệ");
        }
        try {
            inputInfo.setInputPrice(Float.parseFloat(txtinputPrince.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Giá nhập không hợp lệ");
        }
        try {
            inputInfo.setOutputPrice(Float.parseFloat(txtOutputPrice.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Giá nhập không hợp lệ");
        }
        try {
            inputInfo.setOutputPrice(Float.parseFloat(txtOutputPrice.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Giá nhập không hợp lệ");
        }

        inputInfo.setInputInfoStatus(txtStatus.getText());
        if (new DAO().addInputInfo(inputInfo)) {
            JOptionPane.showMessageDialog(rootPane, "Thêm phiếu nhập sản phẩm thành công!");
            list.add(inputInfo);
            showResultInputView();
            //           model.setRowCount(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thêm phiếu nhập sản phẩm thất bại,vui lòng kiểm tra lại thông tin!");
        }

    }//GEN-LAST:event_btnAddinputInfoActionPerformed

    private void btnDeleteInputInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInputInfoActionPerformed
      int selectedRow = InputInfoTable.getSelectedRow();
      
      
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu nhập sản phẩm để xóa");
            return;
        }
        
        
        int inputInfoId = (int) model.getValueAt(selectedRow, 1);
        
        if (new DAO().deleteInputInfoId(inputInfoId)) {
            JOptionPane.showMessageDialog(this, "Xóa phiếu nhập sản phẩm thành công");
            list = new DAO().getListInputInfo();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa phiếu nhập sản phẩm không thành công");}
    }//GEN-LAST:event_btnDeleteInputInfoActionPerformed

    
    public void showResultInputView(){
            InputInfo inputInfo = list.get(list.size()-1);
        model.addRow(new Object[]{
            i++,inputInfo.getInputInfoId(),inputInfo.getItemId(),inputInfo.getInputId(),inputInfo.getQuantity(),inputInfo.getInputPrice(),inputInfo.getOutputPrice(),inputInfo.getInputInfoStatus()

        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputInfoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InputInfoTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnAddinputInfo;
    private javax.swing.JButton btnDeleteInputInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtIInputInfoId;
    private javax.swing.JTextField txtInputId2;
    private javax.swing.JTextField txtOutputPrice;
    private javax.swing.JTextPane txtQuantityInput;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtinputPrince;
    private javax.swing.JTextField txtitemId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
     e.getSource().equals(back) ;
    backClick();
        }

    private void backClick() {
       new InPutView().setVisible(true);
       this.dispose();
    }
        
    


}
