/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Input;
import model.InputInfo;

/**
 *
 * @author khact
 */
public class InPutView extends javax.swing.JFrame implements ActionListener {

    private ArrayList<Input> list;
    private ArrayList<InputInfo> listinfo;
    DefaultTableModel model;

    /**
     * Creates new form InPutView
     */
    public InPutView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý nhập");
        back.addActionListener(this);
        btnInputInfoView.addActionListener(this);
        list = new DAO().getLisInput();
        model = (DefaultTableModel) InputTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã phiếu nhập", "Ngày tạo"
        });
        showtableInput();
    }

    public void showtableInput() {
        for (Input input : list) {
            model.addRow(new Object[]{
                i++, input.getInputId(), input.getInputDate()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputTable = new javax.swing.JTable();
        txtInputId = new javax.swing.JTextField();
        txtInputDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddInput = new javax.swing.JButton();
        btnDeleteInput = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnInputInfoView = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PHIẾU NHẬP");

        InputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(InputTable);

        jLabel2.setText("Mã phiếu nhập");

        jLabel3.setText("Ngày tạo");

        btnAddInput.setText("Thêm phiếu nhập");
        btnAddInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddInputActionPerformed(evt);
            }
        });

        btnDeleteInput.setText("Xóa phiếu nhập");
        btnDeleteInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInputActionPerformed(evt);
            }
        });

        btnInputInfoView.setText("Thông tin phiếu nhập");

        back.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(771, 771, 771)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtInputDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInputId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteInput, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnInputInfoView)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtInputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(txtInputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(32, 32, 32)
                        .addComponent(btnAddInput)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteInput)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(back))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnInputInfoView)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddInputActionPerformed
        Input input = new Input();
        if (txtInputId.getText().equals("") || txtInputDate.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin");
        } else {
            try {
                input.setInputId(Integer.parseInt(txtInputId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Mã phiếu nhập chỉ nhận kí tự số và là duy nhất");

            }
            try {
                input.setInputDate(new SimpleDateFormat("dd/MM/yyyy").parse(txtInputDate.getText()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ngày tạo không hợp lệ ");
            }
            if (new DAO().addInput(input)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu nhập thành công!");
                list.add(input);
                showResultInputView();
//           model.setRowCount(0);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu nhập thất bại,vui lòng kiểm tra lại thông tin!");
            }
        }
    }//GEN-LAST:event_btnAddInputActionPerformed

    private void btnDeleteInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInputActionPerformed
        int selectedRow = InputTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu nhập để xóa");
            return;
        }
        int inputId = (int) model.getValueAt(selectedRow, 1);

        if (new DAO().deleteInput(inputId)) {
            JOptionPane.showMessageDialog(this, "Xóa phiếu nhập thành công");
            list = new DAO().getLisInput();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa phiếu nhạp không thành công");
        }

    }//GEN-LAST:event_btnDeleteInputActionPerformed

    int i = 1;

    public void showResultInputView() {
        Input input = list.get(list.size() - 1);
        model.addRow(new Object[]{
            i++, input.getInputId(), input.getInputDate()

        });

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InPutView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InPutView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InPutView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InPutView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InPutView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InputTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnAddInput;
    private javax.swing.JButton btnDeleteInput;
    private javax.swing.JButton btnInputInfoView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtInputDate;
    private javax.swing.JTextField txtInputId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnInputInfoView)) {
            btnInputInfoViewClick();}
        
        if (e.getSource().equals(back)) {
           backClick();
        }
        
      
    }

    private void btnInputInfoViewClick() {
        new InputInfoView().setVisible(true);
        dispose();
    }

    private void backClick() {
        new IOView().setVisible(true);
        dispose();
    }
}
