/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author khact
 */
public class Menu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu");
        //bắt sự kiện của nút
        bttdanhsachdonhang.addActionListener(this);
        bttdanhsachkhachhang.addActionListener(this);
        bttdanhsachnhacungcap.addActionListener(this);
        bttdanhsachsanpham.addActionListener(this);
        logout.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttdanhsachsanpham = new javax.swing.JButton();
        bttdanhsachnhacungcap = new javax.swing.JButton();
        bttdanhsachkhachhang = new javax.swing.JButton();
        bttdanhsachdonhang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttdanhsachsanpham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bttdanhsachsanpham.setText("Danh sách sản phẩm");
        bttdanhsachsanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttdanhsachsanphamActionPerformed(evt);
            }
        });

        bttdanhsachnhacungcap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bttdanhsachnhacungcap.setText("Danh sách nhà cung cấp");

        bttdanhsachkhachhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bttdanhsachkhachhang.setText("Danh sách khách hàng");

        bttdanhsachdonhang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bttdanhsachdonhang.setText("Danh sách đơn hàng");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH QUẢN LÝ ");

        logout.setText("LOG OUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bttdanhsachnhacungcap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttdanhsachkhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttdanhsachdonhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttdanhsachsanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(bttdanhsachsanpham)
                .addGap(26, 26, 26)
                .addComponent(bttdanhsachnhacungcap)
                .addGap(34, 34, 34)
                .addComponent(bttdanhsachkhachhang)
                .addGap(31, 31, 31)
                .addComponent(bttdanhsachdonhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttdanhsachsanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttdanhsachsanphamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttdanhsachsanphamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttdanhsachdonhang;
    private javax.swing.JButton bttdanhsachkhachhang;
    private javax.swing.JButton bttdanhsachnhacungcap;
    private javax.swing.JButton bttdanhsachsanpham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(bttdanhsachsanpham)){
            bttDsSanphamClick();
        }
        else if (e.getSource().equals(bttdanhsachdonhang)){
            bttDsDonhang();
        }
        else if (e.getSource().equals(bttdanhsachkhachhang)){
            bttDsKhachHangClick();
        }
       else if (e.getSource().equals(logout)){
            logoutClick();
        }
        else{
            bttDsNhacungcap();
        }
        
        
    }
    
    public void bttDsKhachHangClick(){
    new CustomerView().setVisible(true);
    this.dispose();
    }
    public void bttDsSanphamClick(){
    new ItemView().setVisible(true);
    this.dispose();
    }
    public void bttDsNhacungcap(){
    new SuplierView().setVisible(true);
    this.dispose();
    }
    public void bttDsDonhang(){
    new IOView().setVisible(true);
    this.dispose();
    }

   

    private void logoutClick() {
        new LoginView().setVisible(true);
        this.dispose();
    }
}
