/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAO;
import com.sun.jdi.connect.ListeningConnector;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import model.Output;

/**
 *
 * @author khact
 */
public class OutPutView extends javax.swing.JFrame implements ActionListener {

    private ArrayList<Output> list;
    DefaultTableModel model;

    /**
     * Creates new form OutPutView
     */
    public OutPutView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý xuất kho");
        btnOutputInfoView.addActionListener(this);
        back.addActionListener(this);
        list = new DAO().getListOutnput();
        model = (DefaultTableModel) OutputTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã phiếu xuất", "Ngày tạo"
        });
        showtableOutput();
    }

    public void showtableOutput() {

        for (Output output : list) {
            model.addRow(new Object[]{
                i++, output.getOutputId(), output.getOutputDate()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtOutputtId = new javax.swing.JTextField();
        txtOutputDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAddOutput = new javax.swing.JButton();
        btnDeleteOutput = new javax.swing.JButton();
        btnOutputInfoView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputTable = new javax.swing.JTable();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Mã phiếu xuất");

        jLabel1.setText("PHIẾU XUẤT");

        jLabel3.setText("Ngày tạo");

        btnAddOutput.setText("Thêm phiếu xuất");
        btnAddOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOutputActionPerformed(evt);
            }
        });

        btnDeleteOutput.setText("Xóa phiếu xuất");
        btnDeleteOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOutputActionPerformed(evt);
            }
        });

        btnOutputInfoView.setText("Thông tin phiếu xuất");

        OutputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(OutputTable);

        back.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnOutputInfoView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(back)
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1)))
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(425, 425, 425)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(28, 28, 28)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtOutputDate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtOutputtId, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAddOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(78, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOutputInfoView)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtOutputtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addComponent(txtOutputDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addGap(32, 32, 32)
                    .addComponent(btnAddOutput)
                    .addGap(18, 18, 18)
                    .addComponent(btnDeleteOutput)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOutputActionPerformed
        Output output = new Output();
        if (txtOutputtId.getText().equals("") || txtOutputDate.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đủ thông tin");
        } else {
            try {
                output.setOutputId(Integer.parseInt(txtOutputtId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Mã phiếu xuất chỉ nhận kí tự số và là duy nhất");

            }
            try {
                output.setOutputDate(new SimpleDateFormat("dd/MM/yyyy").parse(txtOutputDate.getText()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ngày tạo không hợp lệ ");
            }
            if (new DAO().addOutput(output)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu xuất thành công!");
                list.add(output);
                showResultOutputView();
//           model.setRowCount(0);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu nhập thất bại,vui lòng kiểm tra lại thông tin!");
            }
        }
    }//GEN-LAST:event_btnAddOutputActionPerformed
    int i = 1;

    public void showResultOutputView() {

        Output output = list.get(list.size() - 1);
        model.addRow(new Object[]{
            i++, output.getOutputId(), output.getOutputDate()

        });

    }
    private void btnDeleteOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOutputActionPerformed
        int selectedRow = OutputTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn để xóa");
            return;
        }
        int ouputId = (int) model.getValueAt(selectedRow, 1);
        
        if (new DAO().deleteOutput(ouputId)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            list = new DAO().getListOutnput();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm không thành công");

        }
    }//GEN-LAST:event_btnDeleteOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutPutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutPutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutPutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutPutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutPutView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OutputTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnAddOutput;
    private javax.swing.JButton btnDeleteOutput;
    private javax.swing.JButton btnOutputInfoView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtOutputDate;
    private javax.swing.JTextField txtOutputtId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnOutputInfoView)) {
            btnOutputInfoViewClick();
        }
        if (e.getSource().equals(back)) {
            backClick();
        }

    }

    private void btnOutputInfoViewClick() {
        new OutputInfoView().setVisible(true);
        this.dispose();
    }

    private void backClick() {
       new IOView().setVisible(true);
       this.dispose();
    }
}
