/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAO;
import java.awt.Image;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.OutPutInfo;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khact
 */
public class OutputInfoView extends javax.swing.JFrame implements ActionListener{
    private ArrayList<OutPutInfo> list;
    DefaultTableModel model;
    /**
     * Creates new form OutputInfo
     */
    public OutputInfoView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý phiếu xuất");
        back.addActionListener(this);
        list = new DAO().getListOutputInfo();
        model = (DefaultTableModel) OutputInfoTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã xuất sản phẩm","Mã sản phẩm","Mã nhập sản phẩm","Mã phiếu xuất",
       "Số lượng xuất","Mã khách hàng","Ngày xuất","Trạng thái"
        });
        showtableOutputInfoView();
    }

    @Override
    public boolean imageUpdate(Image img, int infoflags, int x, int y, int w, int h) {
        return super.imageUpdate(img, infoflags, x, y, w, h); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
int i =1 ;
    public void showtableOutputInfoView(){
                   for (OutPutInfo outPutInfo : list) {
            model.addRow(new Object[]{
                i++,outPutInfo.getOutputInfoId(),outPutInfo.getItemId(),outPutInfo.getInputInforId(),
                outPutInfo.getOutputId(),outPutInfo.getQuantity(),outPutInfo.getCustomerId(),outPutInfo.getOutputInfoDate(),
                outPutInfo.getOuputInfoStatus()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtcustomerId = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnAddinputInfo = new javax.swing.JButton();
        txtOutputId = new javax.swing.JTextField();
        btnDeleteInputInfo = new javax.swing.JButton();
        txtInputInfoId = new javax.swing.JTextField();
        txtitemId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOuputInfoId = new javax.swing.JTextField();
        txtOutputInfoDate = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutputInfoTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtStatis = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã sản phẩm");

        jLabel4.setText("SẢN PHẨM XUẤT");

        jLabel9.setText("Mã phiếu xuất");

        jScrollPane3.setViewportView(txtcustomerId);

        jLabel10.setText("Số lượng");

        jLabel11.setText("Mã khách hàng");

        jLabel6.setText("Mã xuất sản phẩm");

        jLabel12.setText("Ngày xuất");

        btnAddinputInfo.setText("Thêm sản phẩm xuất");
        btnAddinputInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddinputInfoActionPerformed(evt);
            }
        });

        btnDeleteInputInfo.setText("Xóa sản phẩm xuất");
        btnDeleteInputInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteInputInfoActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã nhập sản phẩm");

        OutputInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(OutputInfoTable);

        jLabel13.setText("Trạng thái");

        back.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAddinputInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteInputInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(202, 202, 202))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtitemId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOuputInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInputInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOutputId, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOutputInfoDate, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStatis, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)))))
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOuputInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtitemId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInputInfoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOutputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOutputInfoDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStatis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddinputInfo)
                            .addComponent(btnDeleteInputInfo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddinputInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddinputInfoActionPerformed
        OutPutInfo outputInfo = new OutPutInfo();
        if (txtOuputInfoId.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng đủ thông tin");
        } else {
            try {
                outputInfo.setOutputInfoId(Integer.parseInt(txtOuputInfoId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Mã xuất sản phẩm chỉ nhận kí tự số và là duy nhất");
            }
            try {
                outputInfo.setItemId(Integer.parseInt(txtitemId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã sản phẩm là số");
            }

            try {
                outputInfo.setInputInforId(Integer.parseInt(txtInputInfoId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã nhập sản phẩm là số");
            }
            try {
                outputInfo.setOutputId(Integer.parseInt(txtOutputId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã phiếu suất sản phẩm là số");
            }
            try {
                outputInfo.setQuantity(Float.parseFloat(txtQuantity.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập số lượng sản phẩm là số");
            }
            try {
                outputInfo.setCustomerId(Integer.parseInt(txtcustomerId.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập mã khách hàng sản phẩm là số");
            }
            try {
                outputInfo.setOutputInfoDate(new SimpleDateFormat("dd/MM/yyyy").parse(txtOutputInfoDate.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đúng định dạnh thời gian xuất");
            }
            outputInfo.setOuputInfoStatus(txtStatis.getText());

            if (new DAO().addOutputInfo(outputInfo)) {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu xuất sản phẩm thành công!");
                list.add(outputInfo);
                showResultOutputInfoView();

            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm phiếu xuất sản phẩm thất bại,vui lòng kiểm tra lại thông tin!");
            }

        }


    }//GEN-LAST:event_btnAddinputInfoActionPerformed

    public void showResultOutputInfoView(){
                OutPutInfo outPutInfo= list.get(list.size() - 1);
        model.addRow(new Object[]{
          i++,outPutInfo.getOutputInfoId(),outPutInfo.getItemId(),outPutInfo.getInputInforId(),
                outPutInfo.getOutputId(),outPutInfo.getQuantity(),outPutInfo.getCustomerId(),outPutInfo.getOutputInfoDate(),
                outPutInfo.getOuputInfoStatus()

        });
    }
    private void btnDeleteInputInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteInputInfoActionPerformed
          int selectedRow = OutputInfoTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu xuất sản phẩm để xóa");
            return;
        }
        int outputInfoId = (int) model.getValueAt(selectedRow, 1);

        if (new DAO().deleteInputInfoId(outputInfoId)) {
            JOptionPane.showMessageDialog(this, "Xóa phiếu xuất sản phẩm thành công");
            list = new DAO().getListOutputInfo();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa phiếu xuất sản phẩm không thành công");}
    }//GEN-LAST:event_btnDeleteInputInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputInfoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OutputInfoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OutputInfoTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnAddinputInfo;
    private javax.swing.JButton btnDeleteInputInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtInputInfoId;
    private javax.swing.JTextField txtOuputInfoId;
    private javax.swing.JTextField txtOutputId;
    private javax.swing.JTextField txtOutputInfoDate;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStatis;
    private javax.swing.JTextPane txtcustomerId;
    private javax.swing.JTextField txtitemId;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
               if (e.getSource().equals(back)) {
            backClick();
        }
        
    }
    private void backClick() {
        new OutPutView().setVisible(true);
        this.dispose();
    }
}
