/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.DAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Suplier;

/**
 *
 * @author khact
 */
public class SuplierView extends javax.swing.JFrame implements ActionListener{

    private ArrayList<Suplier> list;
    DefaultTableModel model;

    /**
     * Creates new form SuplierView
     */
    public SuplierView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Quản lý nhà cung cấp");
        back.addActionListener(this);
        list = new DAO().getListSuplier();
        model = (DefaultTableModel) SupTable.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Email", "Thông tin chi tiết", "Ngày tạo"
        });
        showtableSuplier();
    }

    public void showtableSuplier() {
        for (Suplier suplier : list) {
            model.addRow(new Object[]{
                i++, suplier.getSuplierId(), suplier.getSuplierName(), suplier.getSuplierAddress(), suplier.getSuplierPhone(), suplier.getSuplierEmail(), suplier.getSuplierMoreInfo(), suplier.getSuplierContactDate()
            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcusId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SupTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtsupPhone = new javax.swing.JTextField();
        BntAddSup = new javax.swing.JButton();
        txtsupAddress = new javax.swing.JTextField();
        btnDeleteSup = new javax.swing.JButton();
        txtsupMail = new javax.swing.JTextField();
        txtsupContact = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        txtsupMoreinfo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnUpdateSup = new javax.swing.JButton();
        txtsupId = new javax.swing.JTextField();
        txtcsupname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(CustomerTable);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DANH SÁCH NHÀ CUNG CẤP");

        SupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        SupTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(SupTable);

        jLabel6.setText("Số điện thoại:");

        jLabel7.setText("Ngày tạo:");

        jLabel4.setText("Địa chỉ nhà cung cấp:");

        jLabel8.setText("Thông tin chi tiết");

        BntAddSup.setText("Thêm nhà cung cấp");
        BntAddSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntAddSupActionPerformed(evt);
            }
        });

        btnDeleteSup.setText("Xóa nhà cung cấp");
        btnDeleteSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSupActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel9.setText("Email:");

        btnUpdateSup.setText("Cập nhật nhà cung cấp");
        btnUpdateSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSupActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã nhà cung cấp:");

        jLabel5.setText("Tên nhà cung cấp:");

        back.setText("BACK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(214, 214, 214)
                            .addComponent(btnReset))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtsupMoreinfo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsupContact, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtsupPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtsupMail)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BntAddSup)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDeleteSup))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcsupname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsupId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsupAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(67, 67, 67)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateSup)
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3))
                    .addComponent(btnReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcsupname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsupPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsupMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsupAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsupContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtsupMoreinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntAddSup)
                    .addComponent(btnDeleteSup))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateSup)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        txtsupAddress.setText("");
        txtcsupname.setText("");
        txtsupPhone.setText("");
        txtsupMoreinfo.setText("");
        txtsupMail.setText("");
        txtsupContact.setText("");
        txtcsupname.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnUpdateSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSupActionPerformed
//        if (SupTable.getSelectedRow()>0) {
//            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp để chỉnh sửa.;");
//        }
//        else{
//            if(txtcsupname.getText().equals("") || txtsupAddress.getText().equals("")|| txtsupContact.getText().equals("")
//                    || txtsupMoreinfo.getText().equals("") || txtsupPhone.getText().equals("")
//                    || txtsupId.getText().equals("")){
//                JOptionPane.showMessageDialog(rootPane, "Vui lòng nhập đẩy đủ thông tin.");
//                } 
//            else{
//            Suplier suplier = new Suplier();
//                    try {
//            suplier.setSuplierId(Integer.parseInt(txtsupId.getText()));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Mã nhà cung cấp chỉ nhận kí tự số và là duy nhất");
//
//        }
//
//        try {
//            suplier.setSuplierPhone(Integer.parseInt(txtsupPhone.getText()));
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Số điện thoại khách hàng chỉ nhận kí tự số ");
//
//        }
//
//        try {
//            suplier.setSuplierContactDate(new SimpleDateFormat("dd/MM/yyyy").parse(txtsupContact.getText()));
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Ngày tạo không hợp lệ ");
//        }
//
//        suplier.setSuplierAddress(txtsupAddress.getText());
//        suplier.setSuplierName(txtcsupname.getText());
//        suplier.setSuplierMoreInfo(txtsupMoreinfo.getText());
//        suplier.setSuplierEmail(txtsupMail.getText());
//        new DAO().updateSuplier(suplier);
//            
//            
//            }
//        }
//        
    }//GEN-LAST:event_btnUpdateSupActionPerformed

    private void btnDeleteSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupActionPerformed

        int selectedRow = SupTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn nhà cung cấp để xóa");
            return;
        }
        int suplierId = (int) model.getValueAt(selectedRow, 1);
        
        if (new DAO().deleteSuplier(suplierId)) {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công");
            list = new DAO().getListSuplier();
            model.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sản phẩm không thành công");

        }
    }//GEN-LAST:event_btnDeleteSupActionPerformed

    private void BntAddSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntAddSupActionPerformed
        Suplier suplier = new Suplier();

        try {
            suplier.setSuplierId(Integer.parseInt(txtsupId.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Mã nhà cung cấp chỉ nhận kí tự số và là duy nhất");

        }

        try {
            suplier.setSuplierPhone(Integer.parseInt(txtsupPhone.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại khách hàng chỉ nhận kí tự số ");

        }

        try {
            suplier.setSuplierContactDate(new SimpleDateFormat("dd/MM/yyyy").parse(txtsupContact.getText()));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ngày tạo không hợp lệ ");
        }

        suplier.setSuplierAddress(txtsupAddress.getText());
        suplier.setSuplierName(txtcsupname.getText());
        suplier.setSuplierMoreInfo(txtsupMoreinfo.getText());
        suplier.setSuplierEmail(txtsupMail.getText());

        if (new DAO().addSuplier(suplier)) {
            JOptionPane.showMessageDialog(rootPane, "Thêm nhà cung cấp thành công!");
            list.add(suplier);
            showResultSuplierView();
//           model.setRowCount(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thêm nhà cung cấp thất bại,vui lòng kiểm tra lại thông tin!");
        }

    }

    int i = 1;

    public void showResultSuplierView() {
        Suplier suplier = list.get(list.size() - 1);
        model.addRow(new Object[]{
            i++, suplier.getSuplierId(), suplier.getSuplierName(), suplier.getSuplierAddress(), suplier.getSuplierPhone(), suplier.getSuplierEmail(), suplier.getSuplierMoreInfo(), suplier.getSuplierContactDate()

        });
    }//GEN-LAST:event_BntAddSupActionPerformed

    private void SupTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupTableMouseClicked
//    int row =SupTable.getSelectedRow();
//    int col =SupTable.getColumnCount();
////////    int weih =SupTable.getSelectedColumn();
////////    int cal = SupTable.getRowCount();
////////    int suplier
//    Object[] data = new Object[col];
//////    Object[] daObjects= new Object[cal];
////    
//    for(int i =1 ;i<col ; i++){
//    data[i] = SupTable.getValueAt(row, i);
//    txtsupId.setText(data[1].toString());
//    txtcsupname.setText((String) data[2]);
//    txtsupAddress.setText((String) data[3]);
//    txtsupPhone.setText(data[4].toString());
//    txtsupPhone.setText(data[2].toString());
//
//    txtsupMail.setText((String) data[5]);
//    txtsupMoreinfo.setText((String) data[7]);
//    txtsupContact.setText(data[6].toString());    
//    }
//    for (i=1;i<cal;i++){
//    daObjects[i] = SupTable.getValueAt(weih, i);
//    txtsupPhone.setText(data[1].toString());
//    txtsupMail.setText((String) data[2]);
//    }
    }//GEN-LAST:event_SupTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuplierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuplierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuplierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuplierView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuplierView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntAddSup;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JTable SupTable;
    private javax.swing.JButton back;
    private javax.swing.JButton btnDeleteSup;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdateSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtcsupname;
    private javax.swing.JTextField txtcusId;
    private javax.swing.JTextField txtsupAddress;
    private javax.swing.JTextField txtsupContact;
    private javax.swing.JTextField txtsupId;
    private javax.swing.JTextField txtsupMail;
    private javax.swing.JTextField txtsupMoreinfo;
    private javax.swing.JTextField txtsupPhone;
    // End of variables declaration//GEN-END:variables


    @Override
    public void actionPerformed(ActionEvent e) {
      if (e.getSource().equals(back)){
            backClick();
        }
    }
    
    public void backClick(){
    new Menu().setVisible(true);
    this.dispose();

    }

}
